### ISSUE TITLE
Downloading without the baidu netdisc installer

### ISSUE THREAD

**Issue by durrantmm** [RChGO/OVD#1]
Is it possible to download the database without using the baidu netdisc installer? I'd prefer a direct download link if possible.

**Comment by RChGO** [comment]
> Is it possible to download the database without using the baidu netdisc installer? I'd prefer a direct download link if possible.


Can be downloaded from https://github.com/grc145/Temp
#Please note that this's a temporary URL

**Comment by durrantmm** [comment]
Thank you!
